import type { SparePart } from "@/types/inventory";

export const CATEGORIES = [
  "Rulmanlar",
  "Contalar",
  "Keçeler",
  "Bağlantı Elemanları",
  "Dişliler",
  "Kayışlar & Zincirler",
  "Pompalar",
  "Valf & Vanalar",
  "Filtreler",
  "Elektrik & Elektronik",
  "Pnömatik",
  "Hidrolik",
  "Diğer",
];

export const SORT_OPTIONS: { label: string; field: string }[] = [
  { label: "Parça Adı", field: "name" },
  { label: "Parça No", field: "partNumber" },
  { label: "Stok Miktarı", field: "quantity" },
  { label: "Birim Fiyat", field: "unitPrice" },
  { label: "Son Güncelleme", field: "lastUpdated" },
];

export const EXCEL_COLUMNS = [
  { key: "partNumber", header: "Parça No" },
  { key: "name", header: "Parça Adı" },
  { key: "category", header: "Kategori" },
  { key: "quantity", header: "Miktar" },
  { key: "unitPrice", header: "Birim Fiyat (TL)" },
] as const;

export const INITIAL_PARTS_DATA: SparePart[] = [
  {
    id: "1",
    partNumber: "RLM-6205-2RS",
    name: "Rulman 6205-2RS",
    category: "Rulmanlar",
    quantity: 48,
    unitPrice: 125.5,
    lastUpdated: "2026-03-28T08:30:00Z",
    status: "in-stock",
  },
  {
    id: "2",
    partNumber: "CNT-OR-50X3",
    name: "O-Ring 50x3mm NBR",
    category: "Contalar",
    quantity: 7,
    unitPrice: 8.75,
    lastUpdated: "2026-03-30T14:15:00Z",
    status: "in-stock",
  },
  {
    id: "3",
    partNumber: "VSP-M12X50",
    name: "Vida Seti M12x50 8.8",
    category: "Bağlantı Elemanları",
    quantity: 0,
    unitPrice: 3.2,
    lastUpdated: "2026-03-25T10:00:00Z",
    status: "out-of-stock",
  },
  {
    id: "4",
    partNumber: "KYS-V-BELT-B52",
    name: "V-Kayış B52",
    category: "Kayışlar & Zincirler",
    quantity: 15,
    unitPrice: 87.0,
    lastUpdated: "2026-04-01T09:00:00Z",
    status: "in-stock",
  },
  {
    id: "5",
    partNumber: "FLT-HYD-P10",
    name: "Hidrolik Filtre 10 Mikron",
    category: "Filtreler",
    quantity: 3,
    unitPrice: 220.0,
    lastUpdated: "2026-03-29T16:45:00Z",
    status: "in-stock",
  },
  {
    id: "6",
    partNumber: "PMP-CEN-32-160",
    name: "Santrifüj Pompa 32-160",
    category: "Pompalar",
    quantity: 2,
    unitPrice: 3450.0,
    lastUpdated: "2026-04-02T11:30:00Z",
    status: "in-stock",
  },
  {
    id: "7",
    partNumber: "KEC-TC-40X62X10",
    name: "Kaçak Contası TC 40x62x10",
    category: "Keçeler",
    quantity: 22,
    unitPrice: 45.0,
    lastUpdated: "2026-03-27T13:20:00Z",
    status: "in-stock",
  },
  {
    id: "8",
    partNumber: "VLF-SOL-NC-1/2",
    name: "Solenoid Valf NC 1/2\"",
    category: "Valf & Vanalar",
    quantity: 0,
    unitPrice: 680.0,
    lastUpdated: "2026-04-01T15:00:00Z",
    status: "out-of-stock",
  },
];
