import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c1d8e4",
        "inverse-primary": "#5f9efb",
        "tertiary-container": "#d9d7f8",
        "on-error": "#fff7f6",
        primary: "#005db5",
        "primary-dim": "#0052a0",
        "surface-variant": "#dbe4e7",
        error: "#9f403d",
        "secondary-fixed": "#cfe6f2",
        "on-secondary-fixed": "#2d424c",
        "surface-container-high": "#e3e9ec",
        "on-tertiary-fixed": "#383751",
        "inverse-surface": "#0c0f10",
        "on-tertiary-container": "#4a4a65",
        "surface-container-highest": "#dbe4e7",
        "surface-tint": "#005db5",
        secondary: "#4d626c",
        "error-container": "#fe8983",
        "on-primary-fixed-variant": "#005bb0",
        "surface-container-lowest": "#ffffff",
        outline: "#737c7f",
        "on-secondary": "#f2faff",
        "on-error-container": "#752121",
        "primary-fixed-dim": "#bfd5ff",
        "on-background": "#2b3437",
        "surface-dim": "#d1dce0",
        "on-tertiary": "#fbf7ff",
        "primary-fixed": "#d6e3ff",
        "on-secondary-container": "#40555f",
        "on-tertiary-fixed-variant": "#54546f",
        "tertiary-fixed-dim": "#cbc9e9",
        "on-secondary-fixed-variant": "#495f69",
        tertiary: "#5d5c78",
        "surface-container": "#eaeff1",
        "outline-variant": "#abb3b7",
        "secondary-dim": "#415660",
        "on-surface": "#2b3437",
        "on-surface-variant": "#586064",
        "error-dim": "#4e0309",
        "on-primary-fixed": "#003f7d",
        "on-primary-container": "#00519e",
        "primary-container": "#d6e3ff",
        "on-primary": "#f6f7ff",
        surface: "#f8f9fa",
        "inverse-on-surface": "#9b9d9e",
        background: "#f8f9fa",
        "secondary-container": "#cfe6f2",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed": "#d9d7f8",
        "surface-container-low": "#f1f4f6",
        "tertiary-dim": "#51516c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "Manrope", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      boxShadow: {
        ghost: "0 12px 40px rgba(43, 52, 55, 0.06)",
        "ghost-md": "0 8px 24px rgba(43, 52, 55, 0.08)",
        "ghost-lg": "0 16px 48px rgba(43, 52, 55, 0.10)",
      },
      backdropBlur: {
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
